### PR TITLE
Add BOOST_TEST_SOURCES

### PR DESCRIPTION
**Pull request by Flamefire**
This appends additional source files to each test. Useful e.g. in combination with BoostTestJamfile to append e.g. a common "main" cpp file or common headers (for IDEs)

### CODE REVIEW

**Comment by pdimov** [comment]
The general idea is fine, but this should be consistent with all the other variables; called BOOST_TEST_SOURCES and implemented in the same manner.

**Comment by Flamefire** [comment]
I disagree: If you use `boost_test` you have to use the `SOURCES` keyword, that is implicitly required (and currently doesn't make sense to not pass)

The somewhat lengthy name should tell that this is somewhat special: It is added (especially: appended) to the sources passed to `boost_test`

Naming it `BOOST_TEST_SOURCES` suggests that this is the way to specify sources. And implementing it in the same manner would mean prepending it to the `SOURCES` which results in wrong auto-deduced NAMEs

So I would prefer to keep the name and handling as proposed as IMO this fits best the use case intended and the name describes best what it does.

**Comment by Flamefire** [comment]
Any comment?

**Comment by pdimov** [comment]
I already commented, didn't I?

**Comment by Flamefire** [comment]
I was looking for some feedback on the thoughts I had mentioned, especially

> Naming it BOOST_TEST_SOURCES suggests that this is the way to specify sources.

But you still must pass at least one source, hence I found the name better suited.

I implemented an approach where it is named `BOOST_TEST_SOURCES` but the name is still gotten from the `SOURCES` argument. Should be OK I guess.

**Pull request merged**
